/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DEVOPS_SPARK;

import java.util.ArrayList;
import spark.Spark;

public class App {
    static ArrayList<Fruit> fruits = new ArrayList<Fruit>();

   

    public static void main(String[] args) {
        fruits.add(new Fruit("Apfel"));
        fruits.add(new Fruit("Birne"));
        fruits.add(new Fruit("Oli Banane"));

        Spark.get("/fruits/:id/liste", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            String name = fruits.get(id).getName();
            return name + " mag ich";
            });
            
        Spark.get("/fruits/:id/counts", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            return fruits.get(id).getCount();
            });

        Spark.put("/fruits/:id/liste", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            fruits.get(id).count();
            return "ok";});

        // Delete list
        Spark.delete("/fruits/:id", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            fruits.delete(id);
            return "ok";});
                           
    
    }
}
        